name: CI
run-name: CI for ${{ github.actor }} at ${{ github.ref }}

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Type checking with basedpyright
        run: |
          uv sync
          uvx basedpyright@1.39.8

  test:
    needs: type-checking
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14t"
          - "3.15"
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version-file: "pyproject.toml"
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --dev

      - if: ${{ startsWith(matrix.os, 'windows') && !endsWith(matrix.python-version, 't') && !startsWith(matrix.python-version, '3.15')}}
        # Pyside does not have free-threaded binary
        run: uv sync --locked --dev --group gui

      - name: CI debugging env windows
        if: ${{runner.debug == '1' && startsWith(matrix.os, 'windows')}}
        run: |
          $Env:CI_DEBUGGING="1"

      - name: CI debugging env non-windows
        if: ${{runner.debug == '1' && !startsWith(matrix.os, 'windows')}}
        run: |
          export CI_DEBUGGING=1

      - name: Run tests debug mode
        if: ${{runner.debug == '1'}}
        timeout-minutes: 3
        run: |
          uv run pytest -vvl --override-ini=log_cli_level=DEBUG --override-ini=log_cli=true

      - name: Run tests
        if: ${{runner.debug != '1'}}
        timeout-minutes: 3
        run: uv run pytest -vvl

  coverage:
    needs: type-checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version-file: "pyproject.toml"
          python-version: "3.13"

      - name: Run tests with coverage
        timeout-minutes: 5
        run: |
          uv sync --locked --dev
          uv pip install orjson>=3.10.16
          uv run pytest --cov --cov-report=xml --junitxml=junit.xml -o junit_family=legacy  --cov-fail-under=100 --cov-report markdown-append:$GITHUB_STEP_SUMMARY

      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: fleming79/async-kernel
          report_type: coverage

  docs:
    needs: type-checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          version-file: "pyproject.toml"

      - name: Docs build strict
        timeout-minutes: 5
        run: |
          uv sync --group docs
          uv run async-kernel install --name=async-docs --timeout=1
          uv run mkdocs build -s
