name: Generate changelog
# Use this workflow to create a PR that is tagged with the new release version.
# Usage:
# 1. Actions -> Generate changelog-> Run workflow -> set the version tag.
# 2. Pull request -> Update changelog
# This workflow always generates the changelog for the main branch and always force pushes to the changelog branch.
# If there is an error with tag already exists, confirm the tag is the one you and delete the tag manually and try again.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version tag"
        default: "0.1.0-rc0"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Generate changelog
        timeout-minutes: 5
        run: |
          set +e
          git branch -D changelog
          set -e
          git checkout -b changelog
          git tag ${{ github.event.inputs.tag}}
          uvx git-cliff -o CHANGELOG.md --github-repo ${{ github.repository }} --github-token ${{ secrets.GITHUB_TOKEN }}
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push  https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git changelog -f --tags

      - name: Create pull request
        # ref: https://cli.github.com/manual/gh_pr_create
        continue-on-error: true
        run: gh pr create --head changelog --title 'Update changelog' --body 'Changlog by git-cliff. PR by Github action.' --label documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
