name: Generate changelog
# Use this workflow to create a PR that is tagged with the new release version version.
# See contributing.md for further detail.
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Version tag"
        default: "v0.1.0-rc0"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Generate changelog
        timeout-minutes: 5
        run: |
          set +e
          git branch -D changelog
          set -e
          git checkout -b changelog
          uvx git-cliff -o CHANGELOG.md --github-repo ${{ github.repository }} --github-token ${{ secrets.GITHUB_TOKEN }} --tag ${{ github.event.inputs.tag}}
          git config user.name ${{github.triggering_actor}}
          git config user.email ''
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push  https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git changelog -f --tags

      - name: Create pull request
        # ref: https://cli.github.com/manual/gh_pr_create
        continue-on-error: true
        run: gh pr create --head changelog --title 'Update changelog' --body 'Changlog by git-cliff. PR by Github action.' --label documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
