name: Demo
# ref: https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
on:
  push:
jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag_info.outputs.tag }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - run: git tag vt
      - id: tag_info
        name: Tag info
        run: echo "tag=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run 'New release'
