name: Publish docs
on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy dev or latest version
    runs-on: ubuntu-latest
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Tag info
        id: tag_info
        run: echo "tag=$(git tag --points-at HEAD)" >> $GITHUB_OUTPUT

      - name: Install the project
        run: |
          uv sync --group docs
          uv run async-kernel -a async-docs --shell.execute_request_timeout 0.1    # The 'async-docs' kernel is specified as the kernel for mkdocs-jupyter

      - name: Deploy with mike 🚀
        if: ${{steps.tag_info.outputs.tag}}
        run: |
          uv run mike deploy --push --update-aliases ${{steps.tag_info.outputs.tag}} latest
          echo "[Latest version of docs updated (${{steps.tag_info.outputs.tag}})](https://fleming79.github.io/async-kernel/latest/" )>> $GITHUB_STEP_SUMMARY

      - name: Deploy a dev version with mike 🚀
        if: ${{!steps.tag_info.outputs.tag}}
        run: |
          uv run mike deploy --push dev
          echo "[Development version of docs ($(hatch version))](https://fleming79.github.io/async-kernel/dev/" )>> $GITHUB_STEP_SUMMARY
