name: Publish docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy dev or latest version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install the project
        run: |
          uv sync --group docs
          uv run async-kernel -a async-docs --shell.execute_request_timeout 0.1    # The 'async-docs' kernel is specified as the kernel for mkdocs-jupyter

      - name: Options
        id: mike
        run: |
          version=$(uv run hatch version)
          if [[ $version =~ ^.*dev ]]; then
              echo "options=dev"  >> $GITHUB_OUTPUT
          elif [[ $version =~ .*[a-zA-Z] ]]; then
              echo "options=$version pre-release" >> $GITHUB_OUTPUT
          else
              echo "options=$version release" >> $GITHUB_OUTPUT
          fi

      - name: Deploy with mike 🚀
        run: |
          uv run mike deploy --push --update-aliases ${{steps.mike.outputs.options}}
          echo "Docs has been updated for version & aliases: ${{steps.mike.outputs.options}} [view here](https://fleming79.github.io/async-kernel/)." >> $GITHUB_STEP_SUMMARY
